x-default-node: &default-node
  restart: always
  image: gridlocknetwork/guardian-node:latest
  volumes:
    # Mount the .env file if it exists, otherwise the default will be used
    - ./.env:/app/.env:ro
    - ./storage:/app/storage
    - ./node.db:/var/lib/gridlock/node/node.db
  networks:
    - gridlock-net

services:
  # Only three nodes are necessary for a minimal functional setup
  node1:
    <<: *default-node
    container_name: guardian-node-1
    volumes:
      - ./storage/nodes/1:/var/lib/gridlock/node

  node2:
    <<: *default-node
    container_name: guardian-node-2
    command: sh -c "sleep 3 && /app/guardian-node"
    volumes:
      - ./storage/nodes/2:/var/lib/gridlock/node

  node3:
    <<: *default-node
    container_name: guardian-node-3
    command: sh -c "sleep 6 && /app/guardian-node"
    volumes:
      - ./storage/nodes/3:/var/lib/gridlock/node

networks:
  gridlock-net:
    external: true
    name: gridlock-net
