version: "3.7"

x-default-node: &default-node
  restart: always
  build:
    context: .
    dockerfile: Dockerfile
  depends_on:
    - nats

services:
  nats:
    container_name: nats
    image: nats:2.9.15-alpine
    command: "-c /etc/nats/nats.cfg"
    volumes:
      - ./nats:/etc/nats
    ports:
      - "4222:4222"

  # Only three nodes are necessary for a minimal functional setup
  node1:
    <<: *default-node
    container_name: guardian-node-1
    volumes:
      - ./storage/nodes/1:/var/lib/gridlock/node
      - ./.env:/app/.env:ro

  node2:
    <<: *default-node
    container_name: guardian-node-2
    volumes:
      - ./storage/nodes/2:/var/lib/gridlock/node
      - ./.env:/app/.env:ro

  node3:
    <<: *default-node
    container_name: guardian-node-3
    volumes:
      - ./storage/nodes/3:/var/lib/gridlock/node
      - ./.env:/app/.env:ro
