[package]
name = "shared"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
kzen-paillier = "0.4.2"

# Workspace dependencies
serde.workspace = true
uuid.workspace = true
derive_more.workspace = true
anyhow.workspace = true
